#!/bin/bash

stdIn=`cat`

IFS=' ' read -r -a arrayHash <<< "$stdIn"
IFS=' ' read -r -a arrayArquivosModificados <<< `git diff --name-only "${arrayHash[0]}" "${arrayHash[1]}"`
IFS=' ' read -r -a arrayGitFileLock <<< `git show "${arrayHash[1]}:.gitlabfilelock"`

if [ "${#arrayArquivosModificados[@]}" != 0 ] && [ "${#arrayGitFileLock[@]}" != 0 ] ; then
        for element in "${arrayArquivosModificados[@]}"
        do
                for elementSeg in "${arrayGitFileLock[@]}"
                do
                        if [ $element = $elementSeg ] ; then
                                echo "Arquivo $elementSeg nao pode ser modificado"
                                exit 1
                        fi
                done
        done
else
        exit 0
fi
