#!/opt/gitlab/embedded/bin/ruby --disable-gems
# Fix the PATH so that gitlab-shell can find git-upload-pack and friends.
ENV['PATH'] = '/opt/gitlab/bin:/opt/gitlab/embedded/bin:' + ENV['PATH']

#!/usr/bin/env ruby

# This file was placed here by GitLab. It makes sure that your pushed commits
# will be processed properly.

refs = $stdin.read
key_id = ENV.delete('GL_ID')
protocol = ENV.delete('GL_PROTOCOL')
repo_path = Dir.pwd
gl_repository = ENV['GL_REPOSITORY']
def increase_reference_counter(gl_repository, repo_path)
  result = GitlabNet.new.pre_receive(gl_repository)

  result['reference_counter_increased']
end

# Implementacao GitLab File Lock
require 'json'

# declaracao variaveis de uso da api GitLab para consulta de permissoes para determinado projeto
projectId = gl_repository.split("-")[1]
userId = key_id.split("-")[1]
TOKEN = 'teexWvzDmWfSvhHEp27X' # alterar de acordo com o seu projeto
URL = 'localhost' # alterar de acordo com seu projeto
PERMISSOES = [40, 50]
consultaApi = JSON.parse(`curl -s #{URL}/api/v4/projects/#{projectId}/members/#{userId}?private_token=#{TOKEN}`)

# declaracao variaveis para utilizacao de logica de arquivos modificados no push e leitura do arquivo .gitlabfilelock
arrayHash = refs.split(" ")
arrayArquivosModificados = `git diff --no-commit-id --name-only #{arrayHash[0]}..#{arrayHash[1]}`.split(" ")
arrayGitLabFileLock = `git show #{arrayHash[1]}:.gitlabfilelock 2> /dev/null`.split(" ")

isAcessoPermitido = PERMISSOES.include? consultaApi["access_level"]
isValidGitLabFileLock = !arrayGitLabFileLock.nil? && arrayGitLabFileLock.length != 0
existeArquivoComum = (arrayArquivosModificados & arrayGitLabFileLock).length != 0

if ( !isAcessoPermitido && (arrayArquivosModificados.include? '.gitlabfilelock') )
   puts "******************************************************"
   puts "****************** GitLab File Lock ******************"
   puts "Arquivo .gitlabfilelock so pode ser modificado pelo administrador do repositorio"
   puts "******************************************************"
   exit 1
end

if ( !isAcessoPermitido && isValidGitLabFileLock && existeArquivoComum )
   puts "******************************************************"
   puts "****************** GitLab File Lock ******************"
   puts "1) Arquivo travado pelo ADM do repositorio."
   puts "2) Para conseguir realizar o PUSH, reverta o(s) arquivo(s) abaixo informado(s) para a revisao anterior ao commit que o modificou."
   puts "------------------------------------------------------"
   puts (arrayArquivosModificados & arrayGitLabFileLock)
   puts "------------------------------------------------------"
   puts "******************************************************"
   exit 1
end
# Fim implementacao GitLab File Lock

require_relative '../lib/gitlab_custom_hook'
require_relative '../lib/gitlab_access'
require_relative '../lib/gitlab_net'

# It's important that on pre-receive `increase_reference_counter` gets executed
# last so that it only runs if everything else succeeded. On post-receive on the
# other hand, we run GitlabPostReceive first because the push is already done
# and we don't want to skip it if the custom hook fails.
if GitlabAccess.new(gl_repository, repo_path, key_id, refs, protocol).exec &&
    GitlabCustomHook.new(repo_path, key_id).pre_receive(refs) &&
    increase_reference_counter(gl_repository, repo_path)
  exit 0
else
  exit 1
end
